<a href="https://colab.research.google.com/github/Deepika-NRIdegree/Mini-project-1/blob/main/Introduction_to_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [133]:
import numpy as np

In [140]:
arr = np.array([[1,2,3],[4,5,6]])

In [134]:
type(arr)

numpy.ndarray

In [135]:

#dot product _ m x n || n x p
arr1 = np.random.randint(1,2,(3,1))

In [137]:
arr.shape

(2, 3)

In [141]:
arr1.shape

(3, 1)

In [138]:
result = np.dot(arr,arr1)

In [139]:
print(result)

[[ 6]
 [15]]


In [ ]:
r1 = np.random.randint(10,20,(3,3))
print(r1)

[[11 19 17]
 [12 12 10]
 [19 11 15]]


In [ ]:
r2 = np.eye(3)
print(r2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
r1_inv = np.linalg.inv(r1)
result2 = np.dot(r2, r1)
print(result2)

In [ ]:
print(result2)

[[1.1 0.  0. ]
 [0.  1.1 0. ]
 [0.  0.  1.1]]


drive.mount('/content/drive')

In [ ]:
print(result1)

[[1.1 0.  0. ]
 [0.  1.1 0. ]
 [0.  0.  1.1]]


In [ ]:
r1_inv = 1.1
result1 = np.dot(r1,r2)

In [ ]:
#M.I = I.M = N

In [ ]:
#A . B != B . A

In [ ]:
# Mathmatics operations
# +-*/

In [ ]:
t1 = np.random.randint(3, 6, (3, 3))
t2 = np.random.randint(3, 6, (3, 3))

In [ ]:
print(t1)

[[5 5 5]
 [5 5 3]
 [3 5 5]]


In [ ]:
print(t2)

[[4 3 3]
 [5 5 4]
 [3 3 5]]


In [ ]:
t3 = t1 + t2
print(t3)

[[ 9  8  8]
 [10 10  7]
 [ 6  8 10]]


In [ ]:
 # Mathmatical Multiplication
result = np.random.randint

In [ ]:
# Stastical operations

In [ ]:
mean = t3.mean()
mode = t3.max()
median = np.median(t3)
std = np.std(t3)
var = np.var(t3)

In [ ]:
print(mean)
print(mode)
print(median)
print(std)
print(var)

8.444444444444445
10
8.0
1.3425606637327303
1.8024691358024691


In [ ]:
std*std

1.8024691358024694

In [ ]:
# Trigonometric functions

In [ ]:
# sin(x)
# cos(x)
# tan(x)_sin(x)\cos(x)
# cosec _ 1\sin(x)
# sen _ 1\ tan(x)
#
angle = np.array([0,15,30,45,60,75,90,])
# sin(array)
result = np.sin(np.radians(angle))
result1= np.cos(np.radians(angle))
result2= np.tan(np.radians(angle))

In [97]:
print(result)
print(result1)
print(result2)

[0.         0.25881905 0.5        0.70710678 0.8660254  0.96592583
 1.        ]
[1.00000000e+00 9.65925826e-01 8.66025404e-01 7.07106781e-01
 5.00000000e-01 2.58819045e-01 6.12323400e-17]
[0.00000000e+00 2.67949192e-01 5.77350269e-01 1.00000000e+00
 1.73205081e+00 3.73205081e+00 1.63312394e+16]


In [99]:
arr = np.array([1,2,3,4,5,6])

In [101]:
# Reshape the array
reshapedarr = arr.reshape(3,2)

In [102]:
print(reshapedarr)

[[1 2]
 [3 4]
 [5 6]]


In [111]:
arr = np.array([1,2,3,4,5,6])

# Reshape the array
reshapedarr = arr.reshape(3,2)

print(reshapedarr)

# Convert / Flatten any n dim array
flattenedarr = arr.flatten()

print(flattenedarr)

[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


In [120]:
# Stacking the data

arr1 = np.array([1,2,3,4,])
arr2 = np.array([10,20,30,40])
#Vartical Stacking
arr3 = np.vstack((arr1,arr2))
print(f"The shape of arr3 is {arr3.shape}")

# Horizontal Stacking
arr4 = np.hstack((arr1,arr2))
print(f"The Shape of arr4 is{arr4.shape}")
print(arr4)

The shape of arr3 is (2, 4)
The Shape of arr4 is(8,)
[ 1  2  3  4 10 20 30 40]


In [121]:
# Filtering
arr = np.array([10,20,30,40,50,60,70,80])

farr = arr[arr > 40]
print(farr)

[50 60 70 80]
